#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.12
# from Racc grammer file "".
#

require 'racc/parser.rb'


class WikiParser < Racc::Parser

module_eval(<<'...end redmine_wiki.y/module_eval...', 'redmine_wiki.y', 49)
def table_parse(line)
  line.split('|')
end

def dl_parse(line)
  line.split(':')
end

def parse(line)
  @yydebug = false
  @q = []
  until line.empty? do
    case line
    when /\A\r?\n-([^-].*)/
      @q.push([:ITEM_1,$1])
    when /\A\r?\n--([^-].*)/
      @q.push([:ITEM_2,$1])
    when /\A\|(.*)/
      @q.push([:TABLE,$1])
    when /\A\r?\n\:(.*)/
      @q.push([:DL,$1])
    when /\Ah1. (.*)/
      @q.push([:HEADER_1,$1])
    when /\Ah2. (.*)/
      @q.push([:HEADER_2,$1])
    when /\Ah3. (.*)/
      @q.push([:HEADER_3,$1])
    when /\A(https?:\/\/[a-zA-Z0-9\/:%#\$&\?\(\)~\.=\+\-]+)/
      @q.push([:URL,$1])
    when /\A(\r?\n)\r\n/
     @q.push([:NEWLINE,$1])
    when /\A\s+/
      ;
    when /\A[^\n]+/
      word = $&
      @q.push [:STRING,word]
    else
      raise RuntimeError, 'must not happen'
    end
    line = $' #'
  end
  @q.push [ false, '$' ]
  do_parse()
end

def next_token
   @q.shift
end

...end redmine_wiki.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    26,    18,    18,    20,     5,    25,    16,    14,    21,    22,
    23,    24,    18,    20,     5,    25,    16,    14,    21,    22,
    23,    24,    20,    16,    14,    20,    33,    20 ]

racc_action_check = [
     1,     3,     1,     1,     1,     1,     1,     1,     1,     1,
     1,     1,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     4,     6,     7,    18,    26,    32 ]

racc_action_pointer = [
    10,     0,   nil,    -1,    19,   nil,    17,    17,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    22,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    26,   nil,   nil,   nil,
   nil,   nil,    24,   nil ]

racc_action_default = [
   -31,   -31,    -1,    -3,    -4,    -5,    -6,    -7,    -8,    -9,
   -10,   -11,   -12,   -13,   -15,   -16,   -18,   -19,   -21,   -23,
   -25,   -26,   -27,   -28,   -29,   -30,   -31,    -2,   -20,   -24,
   -17,   -14,   -22,    34 ]

racc_goto_table = [
    29,     2,    27,     1,    32,    31,    30,    28,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    29 ]

racc_goto_check = [
    15,     2,     2,     1,     4,    12,    13,    14,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    15 ]

racc_goto_pointer = [
   nil,     3,     1,   nil,   -14,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    -2,     0,     4,    -4 ]

racc_goto_default = [
   nil,   nil,   nil,     3,     4,     6,     7,     8,     9,    10,
    11,    12,    13,    15,    17,    19 ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 13, :_reduce_1,
  2, 13, :_reduce_2,
  1, 14, :_reduce_none,
  1, 14, :_reduce_none,
  1, 14, :_reduce_5,
  1, 14, :_reduce_none,
  1, 14, :_reduce_none,
  1, 14, :_reduce_none,
  1, 14, :_reduce_none,
  1, 14, :_reduce_none,
  1, 14, :_reduce_none,
  1, 14, :_reduce_none,
  1, 18, :_reduce_13,
  2, 18, :_reduce_14,
  1, 24, :_reduce_15,
  1, 17, :_reduce_16,
  2, 17, :_reduce_17,
  1, 25, :_reduce_18,
  1, 15, :_reduce_19,
  2, 15, :_reduce_20,
  1, 26, :_reduce_21,
  2, 26, :_reduce_22,
  1, 16, :_reduce_23,
  2, 16, :_reduce_24,
  1, 27, :_reduce_25,
  1, 19, :_reduce_26,
  1, 20, :_reduce_27,
  1, 21, :_reduce_28,
  1, 22, :_reduce_29,
  1, 23, :_reduce_30 ]

racc_reduce_n = 31

racc_shift_n = 34

racc_token_table = {
  false => 0,
  :error => 1,
  :ITEM_1 => 2,
  :ITEM_2 => 3,
  :STRING => 4,
  :NEWLINE => 5,
  :TABLE => 6,
  :DL => 7,
  :HEADER_1 => 8,
  :HEADER_2 => 9,
  :HEADER_3 => 10,
  :URL => 11 }

racc_nt_base = 12

racc_use_result_var = false

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "ITEM_1",
  "ITEM_2",
  "STRING",
  "NEWLINE",
  "TABLE",
  "DL",
  "HEADER_1",
  "HEADER_2",
  "HEADER_3",
  "URL",
  "$start",
  "bodys",
  "body",
  "item1_list",
  "item2_list",
  "tablediv",
  "dl_list",
  "header1",
  "header2",
  "header3",
  "url",
  "newline",
  "dl",
  "table",
  "item1",
  "item2" ]

Racc_debug_parser = true

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'redmine_wiki.y', 5)
  def _reduce_1(val, _values)
    [val[0]]
  end
.,.,

module_eval(<<'.,.,', 'redmine_wiki.y', 6)
  def _reduce_2(val, _values)
    val[0].push(val[1]);val[0]
  end
.,.,

# reduce 3 omitted

# reduce 4 omitted

module_eval(<<'.,.,', 'redmine_wiki.y', 10)
  def _reduce_5(val, _values)
    [:text,val[0]]
  end
.,.,

# reduce 6 omitted

# reduce 7 omitted

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

module_eval(<<'.,.,', 'redmine_wiki.y', 19)
  def _reduce_13(val, _values)
    [:dl_list,[val[0]]]
  end
.,.,

module_eval(<<'.,.,', 'redmine_wiki.y', 20)
  def _reduce_14(val, _values)
    val[0][1].push(val[1]);val[0]
  end
.,.,

module_eval(<<'.,.,', 'redmine_wiki.y', 21)
  def _reduce_15(val, _values)
    [:dl,dl_parse(val[0])]
  end
.,.,

module_eval(<<'.,.,', 'redmine_wiki.y', 23)
  def _reduce_16(val, _values)
    [:table,[val[0]]]
  end
.,.,

module_eval(<<'.,.,', 'redmine_wiki.y', 24)
  def _reduce_17(val, _values)
    val[0][1].push(val[1]);val[0]
  end
.,.,

module_eval(<<'.,.,', 'redmine_wiki.y', 26)
  def _reduce_18(val, _values)
    [:row,table_parse(val[0])]
  end
.,.,

module_eval(<<'.,.,', 'redmine_wiki.y', 28)
  def _reduce_19(val, _values)
    [:item1_list,[val[0]]]
  end
.,.,

module_eval(<<'.,.,', 'redmine_wiki.y', 29)
  def _reduce_20(val, _values)
    val[0][1].push(val[1]);val[0]
  end
.,.,

module_eval(<<'.,.,', 'redmine_wiki.y', 31)
  def _reduce_21(val, _values)
    [:item_1,val[0]]
  end
.,.,

module_eval(<<'.,.,', 'redmine_wiki.y', 32)
  def _reduce_22(val, _values)
    [:item1,val[0],val[1]]
  end
.,.,

module_eval(<<'.,.,', 'redmine_wiki.y', 34)
  def _reduce_23(val, _values)
    [:item2_list,[val[0]]]
  end
.,.,

module_eval(<<'.,.,', 'redmine_wiki.y', 35)
  def _reduce_24(val, _values)
    val[0][1].push(val[1]);val[0]
  end
.,.,

module_eval(<<'.,.,', 'redmine_wiki.y', 36)
  def _reduce_25(val, _values)
    [:item_2,val[0]]
  end
.,.,

module_eval(<<'.,.,', 'redmine_wiki.y', 38)
  def _reduce_26(val, _values)
    [:header_1,val[0]]
  end
.,.,

module_eval(<<'.,.,', 'redmine_wiki.y', 39)
  def _reduce_27(val, _values)
    [:header_2,val[0]]
  end
.,.,

module_eval(<<'.,.,', 'redmine_wiki.y', 40)
  def _reduce_28(val, _values)
    [:header_3,val[0]]
  end
.,.,

module_eval(<<'.,.,', 'redmine_wiki.y', 42)
  def _reduce_29(val, _values)
    [:url,val[0]]
  end
.,.,

module_eval(<<'.,.,', 'redmine_wiki.y', 44)
  def _reduce_30(val, _values)
    [:newline,val[0]]
  end
.,.,

def _reduce_none(val, _values)
  val[0]
end

end   # class WikiParser


